site_name: Directional Scalper Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Strategies: strategies.md
  - Control Center: control_center.md
  - API Reference: api_reference.md
  - Docker: docker.md
  - Telegram Alerts: telegram_alerts.md
